# Generated by Django 5.0.1 on 2026-08-17 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='questions_source',
            field=models.CharField(choices=[('ai_generated', 'AI Generated'), ('user_uploaded', 'User Uploaded')], default='ai_generated', max_length=20),
        ),
        migrations.AddField(
            model_name='session',
            name='user_uploaded_questions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
