# Generated by Django 5.0.1 on 2026-08-17 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_session_questions_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='answer_type',
            field=models.CharField(choices=[('text', 'Text'), ('voice', 'Voice Recording')], default='text', max_length=10),
        ),
        migrations.AddField(
            model_name='answer',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='voice_answers/'),
        ),
        migrations.AddField(
            model_name='answer',
            name='is_transcribed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='answer',
            name='transcribed_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='transcription_confidence',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
