# Generated by Django 5.0.1 on 2026-08-17 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_answer_answer_type_answer_audio_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='subscription_tier',
        ),
    ]
